### ISSUE TITLE
BUG: ab dem 2. Puzzle, wird das puzzle mit 1-2 Klicks gelöst

### ISSUE THREAD

**Issue by FF-5** [Gbitter412/PM_Frauen_historisch#16]
Nachdem man der 1. Puzzle manuell auflöst, bei den nächsten Puzzle hat man den folgenden Verhalten:

- SlidingPuzzle: mit 1 Klick geht man zum nächsten Puzzle
- SwappingPuzzle: mit 2 Klicks geht man zum nächsten Puzzle

Oder auch manchmal nach dem 1. Puzzle mit einem Klick geht man gleich zum nächsten Puzzle.

Zu checken nachdem das Verhalten vom Nächster-Button implementiert wird.

**Comment by Pat368** [comment]
Bug tritt nichtmehr auf, da sich Spielablauf geändert hat
